DEV-672 pages redesign with light/dark mode
rebuschain/rebus.app.web pull request #158
Opened 2023-10-11 15:53 UTC by willmccormick24

2023-10-24 02:32 UTC, Ericky14 approved these changes

2023-10-24 02:52 UTC, Ericky14 requested changes
When you click on an input field it grows in height, let's make the height stay the same unless that's part of the design

<img width="604" alt="Screenshot 2023-10-23 at 10 52 18 PM" src="https://github.com/rebuschain/rebus.app.web/assets/21248862/1cb055b0-ee58-4567-a6ea-2e92e6b640e4">

2023-10-25 14:44 UTC, willmccormick24 commented
> When you click on an input field it grows in height, let's make the height stay the same unless that's part of the design
> 
> <img alt="Screenshot 2023-10-23 at 10 52 18 PM" width="604" src="https://user-images.githubusercontent.com/21248862/277535139-1cb055b0-ee58-4567-a6ea-2e92e6b640e4.png">

@Ericky14 I believe the border is supposed to grow in the design, from 1px to 2px.

2023-10-25 14:54 UTC, Ericky14 approved these changes

2023-10-25 15:22 UTC, merged